[MM-41] : Added the test cases for the todo list generated message.
Brightscout/mattermost-test-management pull request #26
Opened 2023-12-20 11:16 UTC by arush-vashishtha

### Summay
This PR consists the test cases for the updated format of the events in the generated message of Todo list in github.

2023-12-29 09:10 UTC, AayushChaudhary0001 commented on data/test-cases/plugins/github/general/todo_list.md
> +2. Create the desirec event on the connected github repo/organization.
```suggestion
2. Create the desired event on the connected github repo/organization.
```

2023-12-29 09:10 UTC, AayushChaudhary0001 commented on data/test-cases/plugins/github/general/todo_list.md
> +3. Enter the `/github todo` command in any desired channel or DM/GM on MM.
```suggestion
3. Run the `/github todo` command in any desired channel or DM/GM on MM.
```

2023-12-29 09:10 UTC, AayushChaudhary0001 commented on data/test-cases/plugins/github/general/todo_list.md
> +2. Create the desirec event on the connected github repo/organization.
```suggestion
2. Trigger the desirec event on the connected github repo/organization.
```

2024-01-03 07:52 UTC, AayushChaudhary0001 approved these changes

2024-01-11 09:07 UTC, raghavaggarwal2308 requested changes

2024-01-11 09:07 UTC, raghavaggarwal2308 commented on data/test-cases/plugins/github/general/todo_list.md
> +1. Connect your github account to MM and create a subsciption for any desired event discussion, issue, pulls, etc;
```suggestion
1. Connect your github account to MM and create a subsciption for any desired event Eg. discussion, issue, pulls, etc;
```

2024-01-12 11:26 UTC, raghavaggarwal2308 commented on data/test-cases/plugins/github/general/todo_list.md
> +2. Trigger the desired event e.g discussion, issue, pulls, etc on the connected github repo/organization and create notification in the subscribed channel or DM/GM on MM.
```suggestion
2. Create a notification for the desired event e.g. discussion, issue, pulls, etc on GitHub.
```

2024-01-16 10:57 UTC, raghavaggarwal2308 approved these changes

2024-01-16 13:01 UTC, merged