[MM-61]: Added the test cases for the PR 683 with the --exclude flag and for PR 718.
Brightscout/mattermost-test-management pull request #29
Opened 2023-12-27 11:49 UTC by arush-vashishtha

### Summary
This PR consist the test cases for the following PRs,
https://github.com/mattermost/mattermost-plugin-github/pull/718
https://github.com/mattermost/mattermost-plugin-github/pull/683

2024-01-08 12:36 UTC, AayushChaudhary0001 commented on data/test-cases/plugins/github/subscriptions/Exclude_subscriptions_for_repo.md
> +2. Create the desired event in the desired exclude repository on the Github and navigate to the desired channel or DM/GM on MM.
Rephrase this.

2024-01-08 12:36 UTC, AayushChaudhary0001 commented on data/test-cases/plugins/github/subscriptions/Exclude_subscriptions_for_repo.md
> +2. Create the desired event in any desired repository except the excluded ones on the Github and navigate to the desired channel or DM/GM on MM.
Same as above

2024-01-09 12:26 UTC, AayushChaudhary0001 approved these changes

2024-01-10 15:19 UTC, raghavaggarwal2308 requested changes

2024-01-10 15:19 UTC, raghavaggarwal2308 commented on data/test-cases/plugins/github/subscriptions/Re-opened_PR_notification.md
> +# (Required) Ensure all values are filled up
```suggestion
---
# (Required) Ensure all values are filled up
```

2024-01-10 15:19 UTC, raghavaggarwal2308 commented on data/test-cases/plugins/github/subscriptions/Exclude_subscriptions_for_repo.md
> +# (Required) Ensure all values are filled up
```suggestion
---
# (Required) Ensure all values are filled up
```

2024-01-12 11:33 UTC, raghavaggarwal2308 approved these changes

2024-01-12 13:24 UTC, merged