[MM-93]: Added the test cases for the image in the comment notification.
Brightscout/mattermost-test-management pull request #33
Opened 2024-01-05 11:07 UTC by arush-vashishtha

### Summary
This PR consists the test cases for the Image attached to a comment in a issue or merge request on Gitlab.

2024-01-12 13:03 UTC, AayushChaudhary0001 requested changes

2024-01-12 13:03 UTC, AayushChaudhary0001 commented on data/test-cases/plugins/gitlab/subscriptions-and-notifications/Image_in_gitlab_comment.md
> +1. Connect your Gitlab account to MM account.
Same as previous one.

2024-01-12 13:03 UTC, AayushChaudhary0001 commented on data/test-cases/plugins/gitlab/subscriptions-and-notifications/Image_in_gitlab_comment.md
> +3. Navigate to the subscribed repo and add comment with an attachment of an image to any desired `issue` or `merge request` on Gitlab.
repo in gitlab

2024-01-12 13:03 UTC, AayushChaudhary0001 commented on data/test-cases/plugins/gitlab/subscriptions-and-notifications/Image_in_gitlab_comment.md
> +3. Navigate to the subscribed repo and add comment with an attachment of an image to any desired `issue` or `merge request` on Gitlab.
add an image in the comments

2024-01-12 13:03 UTC, AayushChaudhary0001 commented on data/test-cases/plugins/gitlab/subscriptions-and-notifications/Image_in_gitlab_comment.md
> +3. Navigate to the subscribed repo and add comment with an embedded image to any desired `issue` or `merge request` on Gitlab.
same as above

2024-01-16 11:31 UTC, AayushChaudhary0001 approved these changes

2024-01-18 10:02 UTC, raghavaggarwal2308 approved these changes

2024-01-19 06:18 UTC, merged