[MM-96]: Added the test cases for the Settings slash command and zoom icon action in app bar on MM.
Brightscout/mattermost-test-management pull request #34
Opened 2024-01-08 11:34 UTC by arush-vashishtha

### Summary
This PR consists the test cases for the following scenarios,

- When the user uses the Zoom icon from the app bar to create a zoom meeting.
- When the user enter the slash command on MM.

2024-01-12 14:45 UTC, AayushChaudhary0001 requested changes

2024-01-12 14:45 UTC, AayushChaudhary0001 commented on data/test-cases/plugins/zoom/general/Settings_slash_commands.md
> +1. Enter the slash command `/zoom` in the chat in any desired channel or DM/GM on MM.
Try to write enter and run when you do not have any other action in the same step.

2024-01-16 11:42 UTC, AayushChaudhary0001 approved these changes

2024-01-18 10:01 UTC, raghavaggarwal2308 requested changes

2024-01-18 10:01 UTC, raghavaggarwal2308 commented on data/test-cases/plugins/zoom/general/Settings_slash_commands.md
> +1. Enter and run the slash command `/zoom` in the chat in any desired channel or DM/GM on MM.
```suggestion
1. Enter and run the slash command `/zoom` in any desired channel or DM/GM on MM.
```

2024-01-18 10:01 UTC, raghavaggarwal2308 commented on data/test-cases/plugins/zoom/general/Settings_slash_commands.md
> +name: "Settings slash command should not entertain any command after `/zoom settings`"
```suggestion
name: "Settings slash command should not accept any arguments after `/zoom settings`"
```

2024-01-18 10:01 UTC, raghavaggarwal2308 commented on data/test-cases/plugins/zoom/general/Settings_slash_commands.md
> +The suggested list of the commands should show the following suggestions in the desried channel or DM/GM on MM, `start[meeting topic]`, `connect`, `disconnect`, `settings` and `help`.
```suggestion
The suggested list of the commands should show the following suggestions in the desried channel or DM/GM on MM, `start [meeting topic]`, `connect`, `disconnect`, `settings` and `help`.
```

2024-01-18 10:01 UTC, raghavaggarwal2308 commented on data/test-cases/plugins/zoom/general/Settings_slash_commands.md
File name should be `Settings_slash_command.md`

2024-01-18 10:01 UTC, raghavaggarwal2308 commented on data/test-cases/plugins/zoom/general/Zoom_icon_in_app_bar.md
> +name: "Creating meeting through Zoom icon in the App bar/channel header."
```suggestion
name: "Creating meeting using Zoom icon in the app bar/channel header."
```

2024-01-18 10:01 UTC, raghavaggarwal2308 commented on data/test-cases/plugins/zoom/general/Zoom_icon_in_app_bar.md
> +2. Set the Zoom setting by running the slash command `/zoom settings` to `Yes` for using Personal Meeting ID when starting a meeting.
```suggestion
2. Set the Zoom setting by running the slash command `/zoom settings` to `Yes` for using Personal Meeting ID when creating a meeting.
```

2024-01-18 10:01 UTC, raghavaggarwal2308 commented on data/test-cases/plugins/zoom/general/Zoom_icon_in_app_bar.md
> +3. Click on the Zoom icon in the app bar/channel header when there is no other new Zoom meeting in the channel or DM/GM on MM.
```suggestion
3. Click on the Zoom icon in the app bar/channel header when there is no recent Zoom meeting in the channel or DM/GM on MM.
```
Check everywhere

2024-01-18 10:01 UTC, raghavaggarwal2308 commented on data/test-cases/plugins/zoom/general/Zoom_icon_in_app_bar.md
> +2. Set the Zoom setting by running the slash command `/zoom settings` to `Yes` for using Personal Meeting ID when starting a meeting.
Check everywhere

2024-01-18 10:01 UTC, raghavaggarwal2308 commented on data/test-cases/plugins/zoom/general/Zoom_icon_in_app_bar.md
> +After step 2, the user should be navigated to the Zoom meeting wtih Unique Meeting ID on Zoom.
```suggestion
After step 2, the user should be navigated to the Zoom meeting with Unique Meeting ID on Zoom.
```

2024-01-18 10:01 UTC, raghavaggarwal2308 commented on data/test-cases/plugins/zoom/general/Zoom_icon_in_app_bar.md
> +After step 4, the user should get the message about already created Zoom meeting and should get the slack attachment with option to select `Create New Meeting` or `Join Existing Meeting` in the desir
```suggestion
After step 4, the user should get the message about an already created Zoom meeting and should get the slack attachment with the option to select `Create New Meeting` or `Join Existing Meeting` in the desired channel or DM/GM on MM.
```

2024-01-19 13:36 UTC, raghavaggarwal2308 approved these changes

2024-01-22 06:42 UTC, merged